version: "2"

services:
#   postgres:
#     image: postgres:10.0
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER:     aleph
#       POSTGRES_PASSWORD: aleph
#       POSTGRES_DATABASE: aleph

  elasticsearch:
    image: alephdata/platform-elasticsearch:2.1.4
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-log:/var/log

  rabbitmq:
    image: rabbitmq
    hostname: queue
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  convert-document:
    build: services/convert-document
    restart: on-failure
    tmpfs:
      - /tmp
      - /root/.config
    mem_limit: 2g
    expose:
      - 3000

  extract-polyglot:
    build: services/extract-polyglot
    restart: on-failure
    mem_limit: 2g
    expose:
      - 50000

  extract-spacy:
    build: services/extract-spacy
    restart: on-failure
    mem_limit: 2g
    expose:
      - 50000

  worker:
    build: .
    command: celery -A aleph.queues -B -c 4 -l INFO worker
    restart: on-failure
    links:
      - elasticsearch
      - rabbitmq
      - convert-document
      - extract-polyglot
      - extract-spacy
    tmpfs:
      - /tmp
    volumes:
      - archive-data:/data
      - "/:/host"
    env_file:
      - aleph.env

  shell:
    build: .
    command: /bin/bash
    links:
      - elasticsearch
      - rabbitmq
      - convert-document
      - extract-polyglot
      - extract-spacy
      - worker
    tmpfs:
      - /tmp
    volumes:
      - archive-data:/data
      - "./mappings:/aleph/mappings"
      - "/:/host"
    env_file:
      - aleph.env

  beat:
    build: .
    command: celery -A aleph.queues beat -s /var/lib/celerybeat-schedule.db
    links:
      - elasticsearch
      - rabbitmq
      - worker
      - convert-document
      - extract-polyglot
      - extract-spacy
    tmpfs:
      - /tmp
    volumes:
      - archive-data:/data
    env_file:
      - aleph.env

  api:
    build: .
    command: gunicorn -w 8 -b 0.0.0.0:8000 --log-level info --log-file /var/log/gunicorn.log aleph.manage:app
    expose:
      - 8000
    ports:
      - 8000:8000
    links:
      - elasticsearch
      - rabbitmq
      - worker
    tmpfs:
      - /tmp
    volumes:
      - archive-data:/data
    env_file:
      - aleph.env


volumes:
  assets: {}
  archive-data: {}
  rabbitmq-data: {}
  elasticsearch-data: {}
  elasticsearch-log: {}